---
# tasks file for multienv
- name: Set require facts
  set_fact:
    multienv_container_volumes: >
      {{ multienv_container_volumes | default([]) +
      [ multienv_host_multi_path + item + ':' + multienv_container_multi_path + item ] }}
    multienv_container_union_dirs: >
      {{ multienv_container_union_dirs | default([]) +
      [ multienv_container_multi_path + item + ('=RW' if item == multienv_union | last else '=RO') ] }}
    multienv_host_union_dirs: >
      {{ multienv_host_union_dirs | default([]) +
      [ multienv_host_multi_path + item ] }}
  loop: "{{ multienv_union | reverse | list }}"
  tags:
    - always
    - multienv_run

- name: Check directories
  block:
    - name: Check directories in the host
      file:
        dest: "{{ item }}"
        state: directory
      with_items:
        - "{{ multienv_host_mountpoint }}"
        - "{{ multienv_host_multi_path }}"

    - name: Check directories to be merged
      file:
        dest: "{{ item }}"
        state: directory
      with_items: "{{ multienv_host_union_dirs }}"

- name: Copy build files
  copy:
    src: "{{ multienv_container_build_path }}"
    dest: "/tmp/multienv_build"

- include_tasks: docker.yml
  when: not multienv_podman|bool

- include_tasks: podman.yml
  when: multienv_podman|bool
