---
- name: Prepare
  hosts: all
  tasks:
    - name: install apt-transport-https
      apt:
        name: apt-transport-https
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: install docker
      import_role:
        name: geerlingguy.docker

    - name: install python-docker
      package:
        name: python-docker
        state: present
