---
- name: Prepare
  hosts: all
  tasks:
    - name: make / a shared mount - https://github.com/rancher/rancher/issues/12205#issuecomment-385661588
      shell: mount --make-rshared /
      when: ansible_os_family == 'RedHat'

    - name: install apt-transport-https
      apt:
        name: apt-transport-https
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: install docker
      vars:
        docker_install_compose: false
      import_role:
        name: geerlingguy.docker

    - name: install python-docker
      package:
        name: python-docker
        state: present
